name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.6kzpss4 }}
          password: ${{ secrets.3f9e1905-4f06-4726-baf0-d1ce8a23c808 }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: os2021/java-hello-world-from-github-actions:latest
